### ISSUE TITLE
[RFE] Socket enricher for gadgets mixing socket filters and tracing ebpf programs

### ISSUE THREAD

**Issue by alban** [inspektor-gadget/inspektor-gadget#2371]
## Current situation

To use the socket enricher, a gadget has to include:
```
#define GADGET_TYPE_NETWORKING
#include <gadget/sockets-map.h>
```
Or:
```
#define GADGET_TYPE_TRACING
#include <gadget/sockets-map.h>
```
Depending on the gadget type.

See https://inspektor-gadget.io/docs/v0.24.0/reference/gadget-helper-api/#socket-enrichment

## Impact

It's not possible to write a gadget that would use both socket filters and kprobes.

## Ideal future situation

Users can write gadgets containing both kinds of ebpf programs.

## Implementation options

We could have 2 different headers and it should be possible to include them both.

## Additional information

The tcprst gadget might benefit from that: https://github.com/inspektor-gadget/inspektor-gadget/issues/1546

cc @blanquicet

**Comment by moki1202** [comment]
@mauriciovasquezbernal Would simply changing the function names at both these places to `gadget_socket_lookup_networking()` and `gadget_socket_lookup_tracing()` work? I'll update their occurrences accordingly.
```
#ifdef GADGET_TYPE_NETWORKING
static __always_inline struct sockets_value *
gadget_socket_lookup_networking(const struct __sk_buff *skb) 
```

```
#ifdef GADGET_TYPE_TRACING
static __always_inline struct sockets_value *
gadget_socket_lookup_tracing(const struct sock *sk, __u32 netns)
```

**Comment by alban** [comment]
It is fine for me to change the function names to have 2 different names.

But I think that would not "just" compile so easily because the two kinds of gadgets use different kinds of headers:
* tracing programs: use vmlinux.h and kernel internal headers
* networking programs: use uapi kernel headers

I don't think we can use both. Also, I don't know if both set of programs can use the same set of BTF data.

I initially added the "good first issue" label on this issue but now I think that was a bad decision because I don't know how to fix this issue. But you are welcome to give it a try if you want and see if you find solutions.

**Comment by moki1202** [comment]
I'll surf more about it and I'll let you know if I come up with something useful.

**Comment by alban** [comment]
PoC of gadget using both packet capture and uprobes:
https://github.com/alban/trace-udns/pull/1

I couldn't include `<gadget/sockets-map.h>` directly because of duplicate declarations with vmlinux.h but I copied some content over manually.

**Comment by alban** [comment]
I will give this a try.

**Comment by mauriciovasquezbernal** [comment]
@alban was it fixed by #2846?

**Comment by alban** [comment]
> @alban was it fixed by #2846?

Mostly but not completely.

What is done:
* It is now possible to include `sockets-map.h` in a gadget defining both sockets filters and tracing programs.
* It is now possible to call `gadget_socket_lookup()` in one of the ebpf programs

What's missing:
* It is not yet possible to call `gadget_socket_lookup()` in both kinds of ebpf programs

We still have the following code:

```c
#ifdef GADGET_TYPE_NETWORKING
static __always_inline struct sockets_value *
gadget_socket_lookup(const struct __sk_buff *skb)
...
#endif

#ifdef GADGET_TYPE_TRACING
static __always_inline struct sockets_value *
gadget_socket_lookup(const struct sock *sk, __u32 netns)
...
#endif
```

So the following include will generate two functions `gadget_socket_lookup` with different signatures and the compiler would complain about it:
```c
#define GADGET_TYPE_NETWORKING
#define GADGET_TYPE_TRACING
#include <gadget/sockets-map.h>
```

But now it should be easy to implement @moki1202's suggestion from https://github.com/inspektor-gadget/inspektor-gadget/issues/2371#issuecomment-1954252049.
