### ISSUE TITLE
k8s: Prometheus scrap annotations point to the wrong port

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [inspektor-gadget/inspektor-gadget#4371]
The legacy Prometheus implementation added the [scrape annotations ](https://github.com/inspektor-gadget/inspektor-gadget/blob/8d78571d8b12d79ac606b3c82418dbff18475d34/pkg/resources/manifests/deploy.yaml#L148-L151) to make it possible to automatically scrap metrics when using the service discovery on Prometheus. The port's value was hardcoded to 2223, so it doesn't work with the new `--otel-metrics-listen-address` parameter. 

We need to change the logic on deploy.go to automatically change the annotation according to the parameter value.

Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/4366#discussion_r2058647104

**Comment by ghinks** [comment]
I talked to @flyth at Kubecon Europe and did your tutorial class. I will have a stab at this as it looks simple enough for me.

**Comment by ghinks** [comment]
The legacy Prometheus implementation added the scrape annotations to make it possible to automatically scrap metrics
when using the service discovery on Prometheus. The port's value was hardcoded to 2223, so it doesn't work with the new
--otel-metrics-listen-address flag. I am just seeking a bit of advice on how to proceed with this issue.
I am suggesting that the runDeploy function [call to parseK8sYaml for the resources.GadgetDeployment](https://github.com/inspektor-gadget/inspektor-gadget/blob/1d476d053c21c6d27aa3cb5489a2b2da1e826557/cmd/kubectl-gadget/deploy.go#L509) 
is to call this as before but modify the returned runtime object to change the prometheus annotations based on the --otel-metrics-listen-address flag. This could be done by creating a new function that takes the runtime object and the new port and modifies the prometheus annotations and returning the modified runtime object.

something like the following

```go
  objects, err := parseK8sYaml(resources.GadgetDeployment)
  if err != nil {
    return err
  }
  modifiedObjects, err := modifyPrometheusPort(objects, otelMetricsListenAddress)
  if err != nil {
    return err
  }
 ```

**Comment by mqasimsarfraz** [comment]
> This could be done by creating a new function that takes the runtime object and the new port and modifies the prometheus annotations and returning the modified runtime object.

Yes, that sounds correct. You can use `./kubectl-gadget deploy --print-only` to check if your function correctly modifies the port by printing the YAML.

**Comment by ghinks** [comment]
Many thanks , yes that is the testing path I've been using 👍

**Comment by mauriciovasquezbernal** [comment]
@ghinks we already have logic to modify the daemonset on https://github.com/inspektor-gadget/inspektor-gadget/blob/e16644d0e1474729fa4d4f0c35af3b4a22b0d079/cmd/kubectl-gadget/deploy.go#L613, I think your changes can go to that function as well.

**Comment by mauriciovasquezbernal** [comment]
Fixed by #4474

**Comment by mqasimsarfraz** [comment]
It seems the [DaemonSet template](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/charts/gadget/templates/daemonset.yaml#L34) in charts is still using the legacy port. Reopening the issue still we fix it there as well!

**Comment by mauriciovasquezbernal** [comment]
I also learned that it doesn't work when using a configuration file.

**Comment by farhanashrafdev** [comment]
Can I work on it?

**Comment by mqasimsarfraz** [comment]
@farhanashrafdev sure! Assigned! :)

**Comment by DCchoudhury15** [comment]
@mqasimsarfraz if anyone is not actively working on this can i try to solve this issue?

**Comment by farhanashrafdev** [comment]
@mqasimsarfraz I am actually working on this
